apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
# subscription for the Operator, would add it to the operator
# this operator installs an argocd instance for default
metadata:
  name: container-security-operator
  namespace: openshift-operators
spec:
  channel: stable-3.9
  installPlanApproval: Automatic
  name: container-security-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
